<a href="https://colab.research.google.com/github/1502shivam-singh/1502shivam-singh/blob/main/CSSE11_Word2Vec_19147.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### `Submitted by - `[`Shivam Singh (19147)`](19147@iiitu.ac.in)
# Natural language processing (CSSE11)
### Word2Vec implementation with custom corpus (Assignment - 1)

Corpus used - [`"The 18th Letter"`](https://genius.com/Rakim-the-18th-letter-always-and-forever-lyrics) (Hiphop song by Rakim)
<br>
Vocabulary size = 265 (small to medium sized corpus)

Similarity of cells, compared to collab file shared by ma'am are highlighted in top comments of each cell.

In [1]:
#THIS CELL IS IMPORTING LIBRARIES (Same as collab shared by ma'am)

# import tensorflow as tf                  #<------- USING TENSORFLOW 2.0 IS CAUSING AN ERROR. HENCE USING TF VERSION 1.
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()



Instructions for updating:
non-resource variables are not supported in the long term


In [2]:
#IMPORTING DATA: import data from text file corpus (New edits in this section)
from google.colab import files
uploaded = files.upload()
parsedUpload = uploaded["corpus.txt"].decode("utf-8")

#DATA PRE-PROCESSING: Converting to lower-case

corpus = parsedUpload.lower()

parsedWords = []
for parsedWord in corpus.split():
  if parsedWord != ',' and parsedWord != '?':   # lyrics don't have '.' (period) rather they have ','(commas) and '?' (question marks) 
    parsedWords.append(parsedWord)

words = []
words = set(parsedWords)

print(parsedWords)

Saving corpus.txt to corpus.txt
['what', 'uhh', 'yo', 'just', 'when', 'things', 'seemed', 'the', 'same', 'and', 'the', 'whole', 'scene', 'is', 'lame', 'i', 'come', 'and', 'reign', 'with', 'the', 'unexplained', 'for', 'the', 'brains', "'til", 'things', 'change', 'they', 'strain', 'to', 'slang', 'sling', "i'm", 'trained', 'to', 'bring', 'game', 'history', 'that', 'i', 'arranged', 'been', 'regained', 'by', 'king', 'james', 'go', 'to', 'practice', 'with', 'tactics', 'when', 'the', 'track', 'hits', 'theatrics', 'women', 'that', 'look', 'like', 'actress', 'the', 'status', 'of', "cleopatra's", 'stacks', 'of', 'mathematics', 'took', 'the', 'ego-a-geatics', 'as', 'i', 'find', 'out', 'what', 'the', 'facts', 'is', 'for', 'geographic', 'no', 'time', 'to', 'sip', "mo's", 'with', 'hostess', 'never', 'mind', 'what', 'the', 'total', 'gross', 'is', 'i', 'rip', 'shows', 'stay', 'focused', 'and', 'split', 'cheese', 'with', 'soldiers', 'while', 'you', 'hit', 'trees', 'and', 'coast', 'i', 'spit', 'flows', 

In [3]:
#CREATING SENTENCES AS A COMBINATION OF WORDS. (Same as by ma'am)

word2int = {}                                       #creating a Dictionary
int2word = {}
vocab_size = len(words)                             # Gives the total number of unique words

for i,word in enumerate(words):                     #enumerate() method for adding a 'counter' to "words"; starting from 0               
    word2int[word] = i
    int2word[i] = word

print(word2int)
print(int2word)

{'stay': 0, "mind's": 1, 'been': 2, 'no': 3, 'technology': 4, 'shine': 5, 'followers': 6, 'now': 7, 'one': 8, 'look': 9, 'altar': 10, 'you': 11, 'man': 12, 'off': 13, 'planet': 14, 'regained': 15, 'eternity': 16, 'scriptures': 17, 'message': 18, 'hieroglyphics': 19, 'saxophones': 20, 'date': 21, 'bless': 22, 'since': 23, 'they': 24, 'eternally': 25, 'determinely': 26, 'mines': 27, 'mental': 28, 'rip': 29, 'sidestreet': 30, 'r': 31, 'saturn': 32, 'fire': 33, 'only': 34, 'theatrics': 35, 'focused': 36, 'city': 37, 'echo': 38, 'metamorphis': 39, 'ancient': 40, 'vicious': 41, 'it': 42, 'next': 43, 'similar': 44, 'make': 45, 'god': 46, 'like': 47, 'kept': 48, 'prophets': 49, 'strain': 50, 'james': 51, 'skip': 52, 'phrase': 53, 'women': 54, 'we': 55, 'designs': 56, 'trees': 57, 'actress': 58, 'mind': 59, 'scene': 60, 'total': 61, 'letter': 62, 'ego-a-geatics': 63, 'at': 64, 'while': 65, "expectin'": 66, 'together': 67, "allah's": 68, 'which': 69, 'flow-er': 70, 'infirmary': 71, 'for': 72, 's

In [8]:
# New edits in this section 

raw_sentences = corpus.split(',')               # Raw sentences is a list of sentences #split() method splits a string into "list" on basis of separator ','
print(raw_sentences)
sentences = []
for sentence in raw_sentences:
    sentences.append(sentence.replace('?','').split())  # Remove '?' from raw sentence by replacing it with '' (empty character). Then spliting based on spaces
print(sentences)

['what uhh ', ' yo\r\njust when things seemed the same ', " and the whole scene is lame\r\ni come and reign with the unexplained for the brains 'til things change\r\nthey strain to slang sling ", " i'm trained to bring game\r\nhistory that i arranged been regained by king james\r\ngo to practice ", ' with tactics ', ' when the track hits ', " theatrics\r\nwomen that look like actress the status of cleopatra's\r\nstacks of mathematics took the ego-a-geatics ?\r\nas i find out ", ' what the facts is ', " for geographic\r\nno time to sip mo's with hostess ", ' never mind what the total gross is\r\ni rip shows ', ' stay focused ', ' and split cheese ', ' with soldiers\r\nwhile you hit trees and coast i spit flows that be ferocious\r\nand with these explosives ', " i split seas for moses\r\nshine permanently only my mind's concernin' me\r\nfire burns in me eternally time's eternity\r\nfollowers turn on me they'll be in a mental infirmary\r\ndeterminely advance technology better than germany

In [9]:
#MAKING POSITIVE/CONTEXT WORD-PAIRS WITHIN A GIVEN WINDOW SIZE. (Same)

WINDOW_SIZE = 2

data = []
for sentence in sentences:
    for word_index, word in enumerate(sentence):
        for nb_word in sentence[max(word_index - WINDOW_SIZE, 0) : min(word_index + WINDOW_SIZE, len(sentence)) + 1] :    #making neighbor-words pair.
            if nb_word != word:
                data.append([word, nb_word])
print(data)

[['what', 'uhh'], ['uhh', 'what'], ['yo', 'just'], ['yo', 'when'], ['just', 'yo'], ['just', 'when'], ['just', 'things'], ['when', 'yo'], ['when', 'just'], ['when', 'things'], ['when', 'seemed'], ['things', 'just'], ['things', 'when'], ['things', 'seemed'], ['things', 'the'], ['seemed', 'when'], ['seemed', 'things'], ['seemed', 'the'], ['seemed', 'same'], ['the', 'things'], ['the', 'seemed'], ['the', 'same'], ['same', 'seemed'], ['same', 'the'], ['and', 'the'], ['and', 'whole'], ['the', 'and'], ['the', 'whole'], ['the', 'scene'], ['whole', 'and'], ['whole', 'the'], ['whole', 'scene'], ['whole', 'is'], ['scene', 'the'], ['scene', 'whole'], ['scene', 'is'], ['scene', 'lame'], ['is', 'whole'], ['is', 'scene'], ['is', 'lame'], ['is', 'i'], ['lame', 'scene'], ['lame', 'is'], ['lame', 'i'], ['lame', 'come'], ['i', 'is'], ['i', 'lame'], ['i', 'come'], ['i', 'and'], ['come', 'lame'], ['come', 'i'], ['come', 'and'], ['come', 'reign'], ['and', 'i'], ['and', 'come'], ['and', 'reign'], ['and', 'wit

In [10]:
# FUNCTION TO CONVERT WORDS TO 1-HOT VECTORS (Same)

import numpy as np

def to_one_hot(data_point_index, vocab_size):
    temp = np.zeros(vocab_size)                 #np.zeros() will return an Array filled with zeros.
    temp[data_point_index] = 1
    return temp

x_train = []                                    # input word
y_train = []                                    # output word

for data_word in data:
    print(data_word)
    x_train.append(to_one_hot(word2int[ data_word[0] ], vocab_size))
    y_train.append(to_one_hot(word2int[ data_word[1] ], vocab_size))
    
# convert them to numpy arrays
x_train = np.asarray(x_train)
y_train = np.asarray(y_train)


print(x_train[0])
print(y_train[0])
print(x_train.shape)
print(y_train.shape)

['what', 'uhh']
['uhh', 'what']
['yo', 'just']
['yo', 'when']
['just', 'yo']
['just', 'when']
['just', 'things']
['when', 'yo']
['when', 'just']
['when', 'things']
['when', 'seemed']
['things', 'just']
['things', 'when']
['things', 'seemed']
['things', 'the']
['seemed', 'when']
['seemed', 'things']
['seemed', 'the']
['seemed', 'same']
['the', 'things']
['the', 'seemed']
['the', 'same']
['same', 'seemed']
['same', 'the']
['and', 'the']
['and', 'whole']
['the', 'and']
['the', 'whole']
['the', 'scene']
['whole', 'and']
['whole', 'the']
['whole', 'scene']
['whole', 'is']
['scene', 'the']
['scene', 'whole']
['scene', 'is']
['scene', 'lame']
['is', 'whole']
['is', 'scene']
['is', 'lame']
['is', 'i']
['lame', 'scene']
['lame', 'is']
['lame', 'i']
['lame', 'come']
['i', 'is']
['i', 'lame']
['i', 'come']
['i', 'and']
['come', 'lame']
['come', 'i']
['come', 'and']
['come', 'reign']
['and', 'i']
['and', 'come']
['and', 'reign']
['and', 'with']
['reign', 'come']
['reign', 'and']
['reign', 'with']


In [12]:
# MAKING x_train and y_train (Same)

x_input = tf.placeholder(tf.float32, shape=(None, vocab_size))
y_label = tf.placeholder(tf.float32, shape=(None, vocab_size))

In [13]:
# CREATING OUR NEURAL NETWORK: W1, b1, W2, b2 (Same)

EMBEDDING_DIM = 5                                                      

W1 = tf.Variable(tf.random_normal([vocab_size, EMBEDDING_DIM]))
b1 = tf.Variable(tf.random_normal([EMBEDDING_DIM]))                      #bias
hidden_representation = tf.add(tf.matmul(x_input,W1), b1)               

W2 = tf.Variable(tf.random_normal([EMBEDDING_DIM, vocab_size]))
b2 = tf.Variable(tf.random_normal([vocab_size]))
prediction = tf.nn.softmax(tf.add( tf.matmul(hidden_representation, W2), b2))

In [14]:
# CREATING OUR NEURAL NETWORK: LOSS FUNCTION, LEARNING ALGO (GD)

sess = tf.Session()
init = tf.global_variables_initializer()         # Hold the values of variables 'as I told you' (e.g. Random Normal)
sess.run(init)                                                         

cross_entropy_loss = tf.reduce_mean(-tf.reduce_sum(y_train * tf.log(prediction), reduction_indices=[1]))  # The loss function

# define the training step:
train_step = tf.train.GradientDescentOptimizer(0.1).minimize(cross_entropy_loss)

In [15]:
# TRAINING (Increased training iterations)

n = 10000             # train for n iterations

for _ in range(n):
    sess.run(train_step, feed_dict={x_input: x_train, y_label: y_train})
    print('loss is : ', sess.run(cross_entropy_loss, feed_dict={x_input: x_train, y_label: y_train}))

Streaming output truncated to the last 5000 lines.
loss is :  4.664397
loss is :  4.664285
loss is :  4.664174
loss is :  4.664063
loss is :  4.663952
loss is :  4.6638403
loss is :  4.6637297
loss is :  4.6636186
loss is :  4.663507
loss is :  4.663396
loss is :  4.663285
loss is :  4.663174
loss is :  4.6630626
loss is :  4.662952
loss is :  4.662841
loss is :  4.6627297
loss is :  4.662619
loss is :  4.662508
loss is :  4.6623974
loss is :  4.662286
loss is :  4.6621757
loss is :  4.6620646
loss is :  4.661953
loss is :  4.661843
loss is :  4.6617317
loss is :  4.661621
loss is :  4.66151
loss is :  4.661399
loss is :  4.6612883
loss is :  4.6611776
loss is :  4.661067
loss is :  4.6609564
loss is :  4.6608453
loss is :  4.6607347
loss is :  4.6606245
loss is :  4.6605134
loss is :  4.6604033
loss is :  4.6602926
loss is :  4.660181
loss is :  4.660071
loss is :  4.6599603
loss is :  4.65985
loss is :  4.659739
loss is :  4.6596293
loss is :  4.6595187
loss is :  4.659408
loss is : 

In [16]:
# Each row is a real valued vector of 5 terms, representing the words in the vocabulary on the basis of similarity in meaning (Word embeddings)
# Number of Columns = 5 (Size of Hidden Layer)
# Number of Rows = 265 (Vocabulary Size)

vectors = sess.run(W1 + b1)
print(vocab_size)     # Vocabulary Size, also the number of columns         
print(vectors)

265
[[ 1.5582149  -1.0423334   1.488324    1.2335801   0.09369216]
 [ 2.0483778  -0.74913347 -1.2766911   1.1039717   0.28004575]
 [ 0.462244   -0.9551157   0.7570979   0.6092082  -0.4067334 ]
 ...
 [ 1.4151406  -0.0723885  -1.0041959  -0.3704217   2.2052555 ]
 [-1.87973    -0.45432284  0.03229513  0.7380436  -0.7781705 ]
 [-0.07544914  0.02940042  0.9246442   0.3553128   0.78990257]]
